const ACTIONS = {
  PREFETCH_PRODUCTS: 'PREFETCH_PRODUCTS',
  PREPARE_PREFETCH_PRODUCTS: 'PREPARE_PREFETCH_PRODUCTS',
  REVEAL_PRODUCTS: 'REVEAL_PRODUCTS',
  SORT_PRODUCTS: 'SORT_PRODUCTS',
  PREFETCH_STATUS: 'PREFETCH_STATUS',
  REVEAL_INITIAL_PRODUCTS: 'REVEAL_INITIAL_PRODUCTS',
};

export default ACTIONS;
